name: build

on: [pull_request, push]

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name : Validate Gradle Wrapper
        uses : gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Clean Build
        run: ./gradlew clean build
      - name : Archive Artifacts
        uses : actions/upload-artifact@v2
        with :
          name : FastAsyncVoxelSniper-SNAPSHOT
          path : build/libs/*-SNAPSHOT.jar
      - name: Determine release status
        if: ${{ runner.os == 'Linux' }}
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: Publish to Hangar
        if: ${{ runner.os == 'Linux' && env.STATUS == 'release' && github.event_name == 'push' && github.ref == 'refs/heads/tag-2.8.0'}}
        run: ./gradlew publishAllPublicationsToHangar
        env:
         HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
